{% set name = "django-hosts" %}
{% set version = "6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-hosts-{{ version }}.tar.gz
  sha256: e7aec357504d36f384c65fba67deabc4552f36f347b96bb7a3d131a1250d7299

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - django_hosts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://django-hosts.readthedocs.io/
  summary: Dynamic and static host resolving for Django. Maps hostnames to URLconfs.
  dev_url: https://github.com/jazzband/django-hosts
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
